### ISSUE TITLE
Update to changes in tesseract_planning simple planner

### ISSUE THREAD

**Issue by johnwason** [ros-industrial-consortium/tesseract_python#3]
The API has changed for the simple motion planners, breaking the Python build. The SWIG interface needs to be updated to match.

**Comment by Levi-Armstrong** [comment]
I will add a downstream CI build for PR's to help identify these types of breaking changes. I would say mostly everything in the tesseract repository should be stable going forward, but tesseract_planning is likely to change some as we learn more through using it.
